import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar'
import localFont from "next/font/local";

// const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const SchibstedGroteskMedium = localFont({
  src: "./fonts/SchibstedGrotesk-Medium.ttf",
  variable: "--font-SchibstedGroteskMedium",
});
const SchibstedGroteskregular = localFont({
  src: "./fonts/SchibstedGrotesk-Regular.ttf",
  variable: "--font-SchibstedGroteskregular",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${SchibstedGroteskregular.variable} ${SchibstedGroteskMedium.variable} `}>
      <body >

        <div className="flex   ">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
